# -*- coding: utf-8 -*-
"""RID185846_Desafio04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143eAu7QfPWKMghuwYuRhsj5qJmggMdSA

# **ANÁLISE DESCRITIVA**
"""

from google.colab import files
upload = files.upload()

import pandas as pd

df = pd.read_csv("MKT.csv")

df.head()

df.info()

df.describe()

"""# **ANÁLISE EXPLORATIVA**"""

import seaborn as sns
sns.pairplot(df)

sns.pairplot(df, x_vars=['youtube', 'facebook', 'newspaper'], y_vars="sales")

df.corr()

"""# **MODELAGEM**"""

X = df[['youtube', 'facebook', 'newspaper']]
Y = df[['sales']]

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.5, test_size = 0.3, random_state = 95)

print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(X_test.shape)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, Y_train)

y_pred = lr.predict(X_test)

from sklearn.metrics import r2_score
r = r2_score(Y_test, y_pred)
print(r)

import matplotlib.pyplot as plt
grafico = [i for i in range(1, 53, 1)]
fig = plt.figure(figsize=(20,8))
plt.plot(grafico, Y_test, color="blue")
plt.plot(grafico, y_pred, color="red")
plt.xlabel('Index')
plt.ylabel('Sales')

"""# **CALCULANDO PREDIÇÃO**"""

youtube = 125
facebook = 10
newspaper = 17

resultado = [[youtube, facebook, newspaper]]
lr.predict(resultado)[0]